project:
  type: book
  output-dir: docs

book:
  title: "Medición Cohesión Social América Latina"
  author: "Observatorio de Cohesión Social"
  date: "2025"
  chapters:
    - index.qmd
    - intro.qmd
    - cohesion-horizontal.qmd

# bibliography: ocs.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt